-- WezTerm colors — Generated by Matugen
-- Loaded by wezterm.lua via dofile()

return {
  background    = '{{colors.background.default.hex}}',
  foreground    = '{{colors.on_surface.default.hex}}',

  cursor_bg     = '{{colors.primary.default.hex}}',
  cursor_fg     = '{{colors.on_primary.default.hex}}',
  cursor_border = '{{colors.primary.default.hex}}',

  selection_bg  = '{{colors.primary_container.default.hex}}',
  selection_fg  = '{{colors.on_primary_container.default.hex}}',

  -- ANSI colors 0-7
  ansi = {
    '{{colors.surface_dim.default.hex}}',         -- black
    '{{colors.error.default.hex}}',               -- red
    '{{colors.primary.default.hex}}',             -- green
    '{{colors.secondary.default.hex}}',           -- yellow
    '{{colors.tertiary.default.hex}}',            -- blue
    '{{colors.primary_fixed_dim.default.hex}}',   -- magenta
    '{{colors.tertiary_fixed_dim.default.hex}}',  -- cyan
    '{{colors.on_surface.default.hex}}',          -- white
  },

  -- Bright colors 8-15
  brights = {
    '{{colors.surface_variant.default.hex}}',     -- bright black
    '{{colors.error.default.hex}}',               -- bright red
    '{{colors.primary.default.hex}}',             -- bright green
    '{{colors.secondary.default.hex}}',           -- bright yellow
    '{{colors.tertiary.default.hex}}',            -- bright blue
    '{{colors.primary_fixed_dim.default.hex}}',   -- bright magenta
    '{{colors.tertiary_fixed_dim.default.hex}}',  -- bright cyan
    '{{colors.inverse_on_surface.default.hex}}',  -- bright white
  },

  tab_bar = {
    background = '{{colors.surface_dim.default.hex}}',
    active_tab = {
      bg_color = '{{colors.primary_container.default.hex}}',
      fg_color = '{{colors.on_primary_container.default.hex}}',
    },
    inactive_tab = {
      bg_color = '{{colors.surface.default.hex}}',
      fg_color = '{{colors.on_surface_variant.default.hex}}',
    },
    inactive_tab_hover = {
      bg_color = '{{colors.surface_container.default.hex}}',
      fg_color = '{{colors.on_surface.default.hex}}',
    },
    new_tab = {
      bg_color = '{{colors.surface_dim.default.hex}}',
      fg_color = '{{colors.on_surface_variant.default.hex}}',
    },
    new_tab_hover = {
      bg_color = '{{colors.primary.default.hex}}',
      fg_color = '{{colors.on_primary.default.hex}}',
    },
  },
}
