$mainMod = SUPER
$altMod = ALT

bind = $mainMod, RETURN, exec, wezterm  # Terminal emulator
bind = $mainMod, Q, killactive,         # Kill active window

# Switch workspaces
bind = $mainMod, Y, workspace, 1
bind = $mainMod, U, workspace, 2
bind = $mainMod, I, workspace, 3
bind = $mainMod, O, workspace, 4
bind = $mainMod, P, workspace, 5

# Move active window to a workspace
bind = $mainMod SHIFT, Y, movetoworkspace, 1
bind = $mainMod SHIFT, U, movetoworkspace, 2
bind = $mainMod SHIFT, I, movetoworkspace, 3
bind = $mainMod SHIFT, O, movetoworkspace, 4
bind = $mainMod SHIFT, P, movetoworkspace, 5

# Move focused window
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move active window
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d

# Clipboard history
bind = $mainMod, V, exec, doom-clipboard

# Screenshots
bind = $mainMod, PRINT, exec, doom-screenshot smart edit
bind = $mainMod SHIFT, PRINT, exec, doom-screenshot fullscreen clipboard
bind = , PRINT, exec, doom-screenshot smart edit

# Screen Recording
bind = $mainMod, R, exec, doom-screenrecord --with-desktop-audio
bind = $mainMod SHIFT, R, exec, doom-screenrecord --with-desktop-audio --with-microphone-audio

# Bluetooth
bind = $mainMod, B, exec, doom-launch-bluetooth

# Battery info (laptops)
bind = $mainMod CTRL SHIFT, B, exec, notify-send "Battery" "$(doom-battery-remaining)%" -t 2000
