
ecosystem {
  no_update_news = true
  no_donation_nag = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  focus_on_activate = true
  animate_manual_resizes = true
}

workspace = 1, persistent:true

source = $HOME/.config/hypr/envs.conf
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/looknfeel.conf
source = $HOME/.config/hypr/windows.conf
source = $HOME/.config/hypr/bindings.conf
