monitor=,preferred,auto,1

# Examples

# Dual monitor setup
# monitor = DP-1, 2560x1440@75, 1920x0, 1
# monitor = HDMI-1, 1920x1080@60, 0x0, 1

# Laptop screen
# Set laptop screen to the left with preferred resolution and scale 1
# monitor=eDP-1,preferred,0x0,1
# Laptop screen toggle
# bindd = SUPER ALT, H, Laptop screen off, exec, hyprctl keyword monitor "eDP-1,disable"
# bindd = SUPER ALT, l, Laptop screen on , exec, hyprctl keyword monitor "eDP-1, preferred, 0x0, 1"
