#!/bin/bash

if (($# == 0)); then
  echo "Usage: doom-launch-or-focus-webapp [window-pattern] [url-and-flags...]"
  exit 1
fi

WINDOW_PATTERN="$1"
shift
LAUNCH_COMMAND="doom-launch-webapp $@"

exec doom-launch-or-focus "$WINDOW_PATTERN" "$LAUNCH_COMMAND"