-- Matugen color loader for Neovim
-- Applies Material You colors generated by matugen.
-- Reloaded on SIGUSR1 (sent by the matugen post-hook after theme change).

local colors_file = vim.fn.expand('~/.config/matugen/generated/neovim-colors.lua')

local function load_colors()
    if vim.fn.filereadable(colors_file) == 1 then
        dofile(colors_file)
    end
end

load_colors()

-- Re-apply on SIGUSR1 (sent by `pkill -SIGUSR1 nvim` in matugen post-hook)
local ok, uv = pcall(require, 'luv')
if not ok then uv = vim.uv or vim.loop end

if uv then
    local signal = uv.new_signal()
    if signal then
        uv.signal_start(signal, 'sigusr1', function()
            vim.schedule(load_colors)
        end)
    end
end
