-- Neovim colors — Auto-generated by Matugen
-- Applies Material You colors without requiring any plugins.

-- Terminal colors (affects :terminal and color-aware plugins)
vim.g.terminal_color_0  = '{{colors.surface_dim.default.hex}}'
vim.g.terminal_color_1  = '{{colors.error.default.hex}}'
vim.g.terminal_color_2  = '{{colors.primary.default.hex}}'
vim.g.terminal_color_3  = '{{colors.secondary.default.hex}}'
vim.g.terminal_color_4  = '{{colors.tertiary.default.hex}}'
vim.g.terminal_color_5  = '{{colors.primary_fixed_dim.default.hex}}'
vim.g.terminal_color_6  = '{{colors.tertiary_fixed_dim.default.hex}}'
vim.g.terminal_color_7  = '{{colors.on_surface.default.hex}}'
vim.g.terminal_color_8  = '{{colors.surface_variant.default.hex}}'
vim.g.terminal_color_9  = '{{colors.error.default.hex}}'
vim.g.terminal_color_10 = '{{colors.primary.default.hex}}'
vim.g.terminal_color_11 = '{{colors.secondary.default.hex}}'
vim.g.terminal_color_12 = '{{colors.tertiary.default.hex}}'
vim.g.terminal_color_13 = '{{colors.primary_fixed_dim.default.hex}}'
vim.g.terminal_color_14 = '{{colors.tertiary_fixed_dim.default.hex}}'
vim.g.terminal_color_15 = '{{colors.inverse_on_surface.default.hex}}'

-- Core UI
vim.api.nvim_set_hl(0, 'Normal',        { bg = '{{colors.background.default.hex}}',              fg = '{{colors.on_surface.default.hex}}' })
vim.api.nvim_set_hl(0, 'NormalFloat',   { bg = '{{colors.surface_container.default.hex}}',       fg = '{{colors.on_surface.default.hex}}' })
vim.api.nvim_set_hl(0, 'FloatBorder',   { fg = '{{colors.outline.default.hex}}' })
vim.api.nvim_set_hl(0, 'StatusLine',    { bg = '{{colors.surface_container.default.hex}}',       fg = '{{colors.on_surface.default.hex}}' })
vim.api.nvim_set_hl(0, 'StatusLineNC',  { bg = '{{colors.surface_dim.default.hex}}',             fg = '{{colors.on_surface_variant.default.hex}}' })
vim.api.nvim_set_hl(0, 'LineNr',        { fg = '{{colors.outline.default.hex}}' })
vim.api.nvim_set_hl(0, 'CursorLineNr',  { fg = '{{colors.primary.default.hex}}', bold = true })
vim.api.nvim_set_hl(0, 'CursorLine',    { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'ColorColumn',   { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'SignColumn',    { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'WinSeparator',  { fg = '{{colors.outline_variant.default.hex}}' })

-- Selection & Search
vim.api.nvim_set_hl(0, 'Visual',        { bg = '{{colors.primary_container.default.hex}}',       fg = '{{colors.on_primary_container.default.hex}}' })
vim.api.nvim_set_hl(0, 'Search',        { bg = '{{colors.secondary_container.default.hex}}',     fg = '{{colors.on_secondary_container.default.hex}}' })
vim.api.nvim_set_hl(0, 'IncSearch',     { bg = '{{colors.primary.default.hex}}',                 fg = '{{colors.on_primary.default.hex}}' })

-- Syntax
vim.api.nvim_set_hl(0, 'Comment',       { fg = '{{colors.on_tertiary_container.default.hex}}', italic = true })
vim.api.nvim_set_hl(0, 'Keyword',       { fg = '{{colors.inverse_primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'Function',      { fg = '{{colors.secondary.default.hex}}' })
vim.api.nvim_set_hl(0, 'String',        { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'Type',          { fg = '{{colors.tertiary.default.hex}}' })
vim.api.nvim_set_hl(0, 'Constant',      { fg = '{{colors.tertiary_fixed_dim.default.hex}}' })
vim.api.nvim_set_hl(0, 'Identifier',    { fg = '{{colors.on_surface.default.hex}}' })
vim.api.nvim_set_hl(0, 'Error',         { fg = '{{colors.error.default.hex}}' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '{{colors.error.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn',  { fg = '{{colors.secondary.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo',  { fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'DiagnosticHint',  { fg = '{{colors.tertiary.default.hex}}' })

-- Completion menu
vim.api.nvim_set_hl(0, 'Pmenu',         { bg = '{{colors.surface_container.default.hex}}',       fg = '{{colors.on_surface.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuSel',      { bg = '{{colors.primary_container.default.hex}}',       fg = '{{colors.on_primary_container.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuSbar',     { bg = '{{colors.surface_container_high.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuThumb',    { bg = '{{colors.primary.default.hex}}' })

-- Messages
vim.api.nvim_set_hl(0, 'MsgArea',       { bg = '{{colors.surface_container_lowest.default.hex}}', fg = '{{colors.primary.default.hex}}' })
